import type { Campaign, Contact, ContactList, DashboardStats, Automation, AppNotification, DailyMetric, EmailTemplate, Company, Department, User, Role, Employee, Payroll, Timesheet, Vacation, InternalMessage, AdminPost, VideoCallMeeting, BlissProduct, BlissProductDescription, BlissCustomer, BlissOrderStatus, BlissOrder, BlissOrderProduct, MyFormulaProduct, MyFormulaProductDescription, MyFormulaCustomer, MyFormulaOrderStatus, MyFormulaOrder, MyFormulaOrderProduct, MyFormulaQuiz, EspacoAbsolutoCustomer, EspacoAbsolutoAppointment, EspacoAbsolutoUserGroup, EspacoAbsolutoUserMessage, SupportCategory, SupportTicket, FinanceBankAccount, FinanceCategory, FinanceCostCenter, FinanceTransaction, SystemLog, Task, PersonalNote } from '@/types';

// ── Helper ──
const d = (daysAgo: number) => {
  const date = new Date();
  date.setDate(date.getDate() - daysAgo);
  return date.toISOString();
};

// ── Daily Metrics (last 30 days) ──
export const mockDailyMetrics: DailyMetric[] = Array.from({ length: 30 }, (_, i) => {
  const sent = Math.floor(Math.random() * 5000) + 2000;
  const opened = Math.floor(sent * (0.18 + Math.random() * 0.15));
  const clicked = Math.floor(opened * (0.1 + Math.random() * 0.12));
  const bounced = Math.floor(sent * (0.01 + Math.random() * 0.03));
  const date = new Date();
  date.setDate(date.getDate() - (29 - i));
  return {
    date: date.toISOString().split('T')[0],
    sent,
    opened,
    clicked,
    bounced,
  };
});

// ── Dashboard Stats ──
export const mockDashboardStats: DashboardStats = {
  totalSent: 1_284_350,
  openRate: 24.8,
  clickRate: 3.7,
  bounceRate: 1.2,
  totalContacts: 85_420,
  contactGrowth: 12.5,
  dailyMetrics: mockDailyMetrics,
  topCampaigns: [
    { campaignId: '1', campaignName: 'Black Friday Sale', sent: 45000, opened: 13500, clicked: 2700, bounced: 450 },
    { campaignId: '2', campaignName: 'Welcome Series', sent: 32000, opened: 12800, clicked: 3200, bounced: 320 },
    { campaignId: '3', campaignName: 'Product Launch', sent: 28000, opened: 7840, clicked: 1960, bounced: 280 },
    { campaignId: '4', campaignName: 'Monthly Newsletter', sent: 52000, opened: 14560, clicked: 2600, bounced: 520 },
    { campaignId: '5', campaignName: 'Re-engagement', sent: 18000, opened: 3600, clicked: 720, bounced: 900 },
  ],
  heatmapData: Array.from({ length: 7 * 24 }, (_, i) => ({
    day: Math.floor(i / 24),
    hour: i % 24,
    value: Math.floor(Math.random() * 100),
  })),
};

// ── Campaigns ──
export const mockCampaigns: Campaign[] = [
  { id: '1', name: 'Black Friday Sale', subject: '🔥 Up to 70% off - Black Friday Deals', status: 'sent', listId: '1', listName: 'All Subscribers', sentCount: 45000, openRate: 30.0, clickRate: 6.0, bounceRate: 1.0, sentAt: d(5), createdAt: d(10), updatedAt: d(5) },
  { id: '2', name: 'Welcome Series - Day 1', subject: 'Welcome to our community! 🎉', status: 'sent', listId: '2', listName: 'New Users', sentCount: 32000, openRate: 40.0, clickRate: 10.0, bounceRate: 1.0, sentAt: d(3), createdAt: d(15), updatedAt: d(3) },
  { id: '3', name: 'Product Launch - Q1', subject: 'Introducing our newest features', status: 'scheduled', listId: '1', listName: 'All Subscribers', sentCount: 0, openRate: 0, clickRate: 0, bounceRate: 0, scheduledAt: d(-2), createdAt: d(1), updatedAt: d(0) },
  { id: '4', name: 'Monthly Newsletter - Feb', subject: 'Your February roundup is here', status: 'draft', listId: '3', listName: 'Newsletter', sentCount: 0, openRate: 0, clickRate: 0, bounceRate: 0, createdAt: d(0), updatedAt: d(0) },
  { id: '5', name: 'Re-engagement Campaign', subject: 'We miss you! Come back for 20% off', status: 'sending', listId: '4', listName: 'Inactive 90d', sentCount: 8500, openRate: 20.0, clickRate: 4.0, bounceRate: 5.0, createdAt: d(2), updatedAt: d(0) },
  { id: '6', name: 'Holiday Promo 2025', subject: '🎄 Holiday specials inside', status: 'sent', listId: '1', listName: 'All Subscribers', sentCount: 52000, openRate: 28.0, clickRate: 5.5, bounceRate: 1.2, sentAt: d(30), createdAt: d(35), updatedAt: d(30) },
  { id: '7', name: 'Feature Update Announce', subject: 'New dashboard experience', status: 'draft', listId: '2', listName: 'New Users', sentCount: 0, openRate: 0, clickRate: 0, bounceRate: 0, createdAt: d(0), updatedAt: d(0) },
  { id: '8', name: 'Webinar Invitation', subject: 'Join our live webinar this Thursday', status: 'scheduled', listId: '5', listName: 'Webinar List', sentCount: 0, openRate: 0, clickRate: 0, bounceRate: 0, scheduledAt: d(-5), createdAt: d(1), updatedAt: d(0) },
];

// ── Contacts ──
const firstNames = ['Alice', 'Bob', 'Carlos', 'Diana', 'Emma', 'Fábio', 'Gabi', 'Hugo', 'Iris', 'João', 'Karen', 'Lucas', 'Maria', 'Nara', 'Oscar', 'Paula', 'Rafael', 'Sara', 'Tiago', 'Vera'];
const lastNames = ['Silva', 'Santos', 'Oliveira', 'Souza', 'Costa', 'Pereira', 'Lima', 'Ferreira', 'Almeida', 'Ribeiro', 'Martins', 'Rodrigues', 'Gomes', 'Lopes', 'Mendes', 'Carvalho', 'Rocha', 'Araújo', 'Dias', 'Moreira'];
const tagPool = ['VIP', 'Lead', 'Customer', 'Trial', 'Enterprise', 'Churned', 'Newsletter', 'Webinar'];

export const mockContacts: Contact[] = Array.from({ length: 50 }, (_, i) => {
  const fn = firstNames[i % firstNames.length];
  const ln = lastNames[i % lastNames.length];
  const tags = tagPool.filter(() => Math.random() > 0.7);
  return {
    id: `c${i + 1}`,
    email: `${fn.toLowerCase()}.${ln.toLowerCase()}${i}@example.com`,
    name: `${fn} ${ln}`,
    firstName: fn,
    lastName: ln,
    tags: tags.length ? tags : ['Lead'],
    listIds: ['1'],
    status: Math.random() > 0.1 ? 'subscribed' : Math.random() > 0.5 ? 'unsubscribed' : 'bounced',
    createdAt: d(Math.floor(Math.random() * 180)),
    lastActivity: Math.random() > 0.3 ? d(Math.floor(Math.random() * 14)) : undefined,
    openRate: Math.floor(Math.random() * 50 + 10),
    clickRate: Math.floor(Math.random() * 15 + 1),
  };
});

// ── Contact Lists ──
export const mockTemplates: EmailTemplate[] = [
  { id: 't1', name: 'Newsletter Clean', content: '<p>Hello world</p>', createdAt: d(30), updatedAt: d(5) },
  { id: 't2', name: 'Welcome Email', content: '<h1>Welcome!</h1>', createdAt: d(60), updatedAt: d(60) },
  { id: 't3', name: 'Promo Alert', content: '<h2>Special Offer</h2>', createdAt: d(15), updatedAt: d(1) },
];

export const mockLists: ContactList[] = [
  { id: '1', name: 'All Subscribers', contactCount: 85420, createdAt: d(365) },
  { id: '2', name: 'New Users', contactCount: 12300, createdAt: d(200) },
  { id: '3', name: 'Newsletter', contactCount: 45600, createdAt: d(300) },
  { id: '4', name: 'Inactive 90d', contactCount: 8200, createdAt: d(90) },
  { id: '5', name: 'Webinar List', contactCount: 3400, createdAt: d(30) },
];

// ── Automations ──
export const mockAutomations: Automation[] = [
  {
    id: 'a1', name: 'Welcome Series', status: 'active', triggeredCount: 12500, createdAt: d(120),
    nodes: [
      { id: 'n1', type: 'trigger', label: 'User Signs Up', config: {}, position: { x: 0, y: 0 } },
      { id: 'n2', type: 'action', label: 'Send Welcome Email', config: {}, position: { x: 0, y: 100 } },
      { id: 'n3', type: 'delay', label: 'Wait 3 days', config: { days: 3 }, position: { x: 0, y: 200 } },
      { id: 'n4', type: 'condition', label: 'Opened Email?', config: {}, position: { x: 0, y: 300 } },
    ],
    connections: [{ from: 'n1', to: 'n2' }, { from: 'n2', to: 'n3' }, { from: 'n3', to: 'n4' }],
  },
  {
    id: 'a2', name: 'Re-engagement Flow', status: 'paused', triggeredCount: 3200, createdAt: d(60),
    nodes: [
      { id: 'n1', type: 'trigger', label: 'Inactive 30 days', config: {}, position: { x: 0, y: 0 } },
      { id: 'n2', type: 'action', label: 'Send Discount', config: {}, position: { x: 0, y: 100 } },
    ],
    connections: [{ from: 'n1', to: 'n2' }],
  },
  {
    id: 'a3', name: 'Cart Abandonment', status: 'draft', triggeredCount: 0, createdAt: d(5),
    nodes: [],
    connections: [],
  },
];

// ── Notifications ──
export const mockNotifications: AppNotification[] = [
  { id: 'not1', title: 'Campaign Sent', message: 'Black Friday Sale was sent to 45,000 contacts', type: 'success', read: false, createdAt: d(0) },
  { id: 'not2', title: 'High Bounce Rate', message: 'Re-engagement campaign has 5% bounce rate', type: 'warning', read: false, createdAt: d(0) },
  { id: 'not3', title: 'New Subscribers', message: '230 new contacts added today', type: 'info', read: true, createdAt: d(1) },
  { id: 'not4', title: 'Automation Paused', message: 'Re-engagement Flow was paused due to errors', type: 'error', read: true, createdAt: d(2) },
];

export const mockCompanies: Company[] = [
  {
    id: 'cmp1',
    name: 'Bliss Repger',
    slug: 'bliss-repger',
    email: 'geral@blissrepger.com',
    phone: '+351 210 000 000',
    address: 'Lisboa, Portugal',
    logo: null,
    settings: { locale: 'pt-PT' },
    is_active: true,
    createdAt: d(365),
    updatedAt: d(10),
  },
  {
    id: 'cmp2',
    name: 'GMC Solutions',
    slug: 'gmc-solutions',
    email: 'hello@gmc-solutions.example',
    phone: '+351 220 000 000',
    address: 'Porto, Portugal',
    logo: null,
    settings: { locale: 'pt-PT' },
    is_active: true,
    createdAt: d(120),
    updatedAt: d(20),
  },
  {
    id: 'cmp3',
    name: 'Empresa Inativa',
    slug: 'empresa-inativa',
    email: null,
    phone: null,
    address: null,
    logo: null,
    settings: {},
    is_active: false,
    createdAt: d(200),
    updatedAt: d(200),
  },
];

export const mockDepartments: Department[] = [
  {
    id: 'dep1',
    name: 'Suporte',
    slug: 'suporte',
    description: 'Equipa responsável por tickets e atendimento.',
    color: '#22d3ee',
    email: 'suporte@blissrepger.com',
    company_id: 'cmp1',
    is_active: true,
    createdAt: d(200),
    updatedAt: d(5),
  },
  {
    id: 'dep2',
    name: 'Comercial',
    slug: 'comercial',
    description: 'Vendas e relação com clientes.',
    color: '#a78bfa',
    email: 'comercial@blissrepger.com',
    company_id: 'cmp1',
    is_active: true,
    createdAt: d(180),
    updatedAt: d(20),
  },
  {
    id: 'dep3',
    name: 'Suporte',
    slug: 'suporte',
    description: 'Suporte interno da empresa.',
    color: '#fbbf24',
    email: 'helpdesk@gmc-solutions.example',
    company_id: 'cmp2',
    is_active: true,
    createdAt: d(150),
    updatedAt: d(30),
  },
  {
    id: 'dep4',
    name: 'Operações',
    slug: 'operacoes',
    description: null,
    color: '#10b981',
    email: null,
    company_id: 'cmp2',
    is_active: false,
    createdAt: d(90),
    updatedAt: d(90),
  },
];

export const mockSupportCategories: SupportCategory[] = [
  {
    id: 'scat1',
    company_id: 'cmp1',
    name: 'Dúvidas Gerais',
    description: 'Perguntas comuns e esclarecimentos.',
    color: '#3B82F6',
    is_active: true,
    created_at: d(220),
    updated_at: d(10),
  },
  {
    id: 'scat2',
    company_id: 'cmp1',
    name: 'Incidentes',
    description: 'Falhas, bugs e indisponibilidades.',
    color: '#EF4444',
    is_active: true,
    created_at: d(210),
    updated_at: d(5),
  },
  {
    id: 'scat3',
    company_id: 'cmp2',
    name: 'Financeiro',
    description: 'Cobrança, faturas e pagamentos.',
    color: '#F59E0B',
    is_active: true,
    created_at: d(180),
    updated_at: d(12),
  },
  {
    id: 'scat4',
    company_id: 'cmp2',
    name: 'Sugestões',
    description: 'Melhorias e pedidos de funcionalidade.',
    color: '#10B981',
    is_active: false,
    created_at: d(170),
    updated_at: d(30),
  },
];

export const mockSupportTickets: SupportTicket[] = [
  {
    id: 'tkt1',
    company_id: 'cmp1',
    title: 'Erro ao entrar no sistema',
    description: 'Ao efetuar login recebo uma mensagem de erro 500.',
    status: 'open',
    priority: 'high',
    category_id: 'scat2',
    department_id: 'dep1',
    user_id: 'usr2',
    user_type: 'App\\Models\\User',
    assigned_to: 'usr3',
    due_date: d(-1),
    resolved_at: null,
    created_at: d(5),
    updated_at: d(1),
  },
  {
    id: 'tkt2',
    company_id: 'cmp1',
    title: 'Como alterar a palavra-passe?',
    description: 'Não encontro a opção para alterar a palavra-passe no perfil.',
    status: 'pending',
    priority: 'low',
    category_id: 'scat1',
    department_id: 'dep1',
    user_id: 'usr1',
    user_type: 'App\\Models\\User',
    assigned_to: null,
    due_date: null,
    resolved_at: null,
    created_at: d(12),
    updated_at: d(8),
  },
  {
    id: 'tkt3',
    company_id: 'cmp2',
    title: 'Fatura em duplicado',
    description: 'O sistema gerou duas faturas para a mesma transação.',
    status: 'in_progress',
    priority: 'urgent',
    category_id: 'scat3',
    department_id: 'dep3',
    user_id: 'usr4',
    user_type: 'App\\Models\\User',
    assigned_to: 'usr1',
    due_date: d(0),
    resolved_at: null,
    created_at: d(2),
    updated_at: d(0),
  },
  {
    id: 'tkt4',
    company_id: 'cmp2',
    title: 'Pedido de melhoria: exportar relatórios',
    description: 'Seria possível exportar relatórios em CSV e PDF?',
    status: 'resolved',
    priority: 'medium',
    category_id: 'scat4',
    department_id: 'dep3',
    user_id: 'usr2',
    user_type: 'App\\Models\\User',
    assigned_to: 'usr3',
    due_date: null,
    resolved_at: d(20),
    created_at: d(30),
    updated_at: d(20),
  },
];

export const mockUsers: User[] = [
  {
    id: 'usr1',
    name: 'Admin GMCentral',
    email: 'admin@gmcentral.local',
    password: 'secret',
    company_id: 'cmp1',
    department_id: 'dep2',
    role_id: null,
    role: 'admin',
    phone: '+351 910 000 001',
    bio: 'Conta administrativa (mock).',
    photo_path: null,
    is_active: true,
    last_login_at: d(1),
    createdAt: d(120),
    updatedAt: d(1),
  },
  {
    id: 'usr2',
    name: 'Gestor Comercial',
    email: 'manager@gmcentral.local',
    password: 'secret',
    company_id: 'cmp1',
    department_id: 'dep2',
    role_id: null,
    role: 'manager',
    phone: '+351 910 000 002',
    bio: null,
    photo_path: null,
    is_active: true,
    last_login_at: d(7),
    createdAt: d(90),
    updatedAt: d(7),
  },
  {
    id: 'usr3',
    name: 'Agente Suporte',
    email: 'agent@gmcentral.local',
    password: 'secret',
    company_id: 'cmp1',
    department_id: 'dep1',
    role_id: null,
    role: 'agent',
    phone: '+351 910 000 003',
    bio: 'Foco em tickets e atendimento.',
    photo_path: null,
    is_active: true,
    last_login_at: d(3),
    createdAt: d(60),
    updatedAt: d(3),
  },
  {
    id: 'usr4',
    name: 'Utilizador Inativo',
    email: 'inactive@gmcentral.local',
    password: 'secret',
    company_id: 'cmp2',
    department_id: 'dep4',
    role_id: null,
    role: 'customer',
    phone: null,
    bio: null,
    photo_path: null,
    is_active: false,
    last_login_at: null,
    createdAt: d(200),
    updatedAt: d(200),
  },
];

export const mockInternalMessages: InternalMessage[] = [
  {
    id: 'im1',
    thread_id: 'th1',
    from_user_id: 'usr1',
    to_user_id: 'usr2',
    subject: 'Boas-vindas',
    body: 'Bem-vindo ao GMCentral. Qualquer coisa, estou por aqui.',
    folder: 'sent',
    read_at: null,
    sent_at: d(5),
    createdAt: d(5),
    updatedAt: d(5),
  },
  {
    id: 'im2',
    thread_id: 'th1',
    from_user_id: 'usr1',
    to_user_id: 'usr2',
    subject: 'Boas-vindas',
    body: 'Segue também o acesso ao painel e os links úteis.',
    folder: 'sent',
    read_at: null,
    sent_at: d(4),
    createdAt: d(4),
    updatedAt: d(4),
  },
  {
    id: 'im3',
    thread_id: 'th1',
    from_user_id: 'usr2',
    to_user_id: 'usr1',
    subject: 'Re: Boas-vindas',
    body: 'Obrigado! Vou validar hoje e retorno se precisar de algo.',
    folder: 'inbox',
    read_at: d(3),
    sent_at: d(3),
    createdAt: d(3),
    updatedAt: d(3),
  },
];

export const mockAdminPosts: AdminPost[] = [
  {
    id: 'post1',
    title: 'Manutenção programada',
    content: 'Atualização: hoje teremos manutenção às 20:00. Pode haver indisponibilidade de 10–15 min.',
    type: 'announcement',
    priority: 'high',
    is_pinned: true,
    featured_image_url: null,
    youtube_video_url: null,
    attachment_urls: ['https://example.com/status'],
    published_at: d(2),
    expires_at: null,
    likes_count: 1,
    liked_by_me: false,
    author: { id: 'usr1', name: 'Admin' },
    can_pin: true,
    can_manage: true,
    created_at: d(2),
    updated_at: d(2),
  },
  {
    id: 'post2',
    title: 'Relatórios semanais',
    content: 'Lembrete: enviar relatórios semanais até sexta-feira 17:00.',
    type: 'text',
    priority: 'normal',
    is_pinned: false,
    featured_image_url: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=1200&q=80&auto=format&fit=crop',
    youtube_video_url: null,
    attachment_urls: [],
    published_at: d(4),
    expires_at: null,
    likes_count: 2,
    liked_by_me: true,
    author: { id: 'usr2', name: 'Utilizador' },
    can_pin: false,
    can_manage: false,
    created_at: d(4),
    updated_at: d(4),
  },
];

export const mockVideoCallMeetings: VideoCallMeeting[] = [
  {
    id: 'meet1',
    title: 'Daily Standup',
    meet_url: 'https://meet.google.com/abc-defg-hij',
    scheduled_at: d(0),
    created_by: 'usr1',
    createdAt: d(1),
    updatedAt: d(1),
  },
  {
    id: 'meet2',
    title: 'Reunião Comercial',
    meet_url: 'https://meet.google.com/klm-nopq-rst',
    scheduled_at: d(-1),
    created_by: 'usr2',
    createdAt: d(7),
    updatedAt: d(7),
  },
];

export const mockBlissOrderStatuses: BlissOrderStatus[] = [
  { order_status_id: '1', language_id: 1, name: 'Pendente' },
  { order_status_id: '2', language_id: 1, name: 'Em processamento' },
  { order_status_id: '3', language_id: 1, name: 'Enviado' },
  { order_status_id: '5', language_id: 1, name: 'Concluído' },
  { order_status_id: '7', language_id: 1, name: 'Cancelado' },
];

export const mockBlissProducts: BlissProduct[] = [
  {
    product_id: 'p1001',
    model: 'BN-001',
    price: 19.9,
    quantity: 42,
    status: true,
    date_added: d(120),
    date_modified: d(4),
    image: 'catalog/demo/product.jpg',
    image_url: 'https://blissnatura.pt/image/catalog/demo/product.jpg',
    description: { product_id: 'p1001', language_id: 1, name: 'Creme Hidratante', description: 'Hidratação diária para pele sensível.' } satisfies BlissProductDescription,
  },
  {
    product_id: 'p1002',
    model: 'BN-002',
    price: 12.5,
    quantity: 8,
    status: true,
    date_added: d(90),
    date_modified: d(10),
    image: 'catalog/demo/product2.jpg',
    image_url: 'https://blissnatura.pt/image/catalog/demo/product2.jpg',
    description: { product_id: 'p1002', language_id: 1, name: 'Sabonete Natural', description: 'Sabonete artesanal com óleos essenciais.' } satisfies BlissProductDescription,
  },
  {
    product_id: 'p1003',
    model: 'BN-003',
    price: 7.99,
    quantity: 3,
    status: true,
    date_added: d(60),
    date_modified: d(18),
    image: null,
    image_url: null,
    description: { product_id: 'p1003', language_id: 1, name: 'Bálsamo Labial', description: null } satisfies BlissProductDescription,
  },
  {
    product_id: 'p1004',
    model: 'BN-004',
    price: 29.0,
    quantity: 0,
    status: false,
    date_added: d(30),
    date_modified: d(30),
    image: null,
    image_url: null,
    description: { product_id: 'p1004', language_id: 1, name: 'Kit Presente', description: 'Edição limitada (inativo).' } satisfies BlissProductDescription,
  },
];

export const mockBlissCustomers: BlissCustomer[] = [
  {
    customer_id: 'c2001',
    firstname: 'Ana',
    lastname: 'Silva',
    email: 'ana.silva@example.com',
    telephone: '+351 910 111 111',
    status: true,
    date_added: d(200),
  },
  {
    customer_id: 'c2002',
    firstname: 'Bruno',
    lastname: 'Santos',
    email: 'bruno.santos@example.com',
    telephone: '+351 910 222 222',
    status: true,
    date_added: d(120),
  },
  {
    customer_id: 'c2003',
    firstname: 'Carla',
    lastname: 'Oliveira',
    email: 'carla.oliveira@example.com',
    telephone: null,
    status: false,
    date_added: d(80),
  },
];

export const mockBlissOrders: BlissOrder[] = [
  {
    order_id: 'o3001',
    invoice_no: null,
    customer_id: 'c2001',
    firstname: 'Ana',
    lastname: 'Silva',
    email: 'ana.silva@example.com',
    telephone: '+351 910 111 111',
    total: 32.4,
    order_status_id: '2',
    date_added: d(7),
    date_modified: d(6),
    payment_method: 'MBWay',
    shipping_method: 'CTT Expresso',
  },
  {
    order_id: 'o3002',
    invoice_no: null,
    customer_id: 'c2002',
    firstname: 'Bruno',
    lastname: 'Santos',
    email: 'bruno.santos@example.com',
    telephone: '+351 910 222 222',
    total: 19.9,
    order_status_id: '3',
    date_added: d(12),
    date_modified: d(10),
    payment_method: 'Cartão',
    shipping_method: 'CTT',
  },
  {
    order_id: 'o3003',
    invoice_no: null,
    customer_id: 'c2003',
    firstname: 'Carla',
    lastname: 'Oliveira',
    email: 'carla.oliveira@example.com',
    telephone: null,
    total: 7.99,
    order_status_id: '7',
    date_added: d(25),
    date_modified: d(24),
    payment_method: 'Referência Multibanco',
    shipping_method: 'CTT',
  },
];

export const mockBlissOrderProducts: BlissOrderProduct[] = [
  {
    order_product_id: 'op1',
    order_id: 'o3001',
    product_id: 'p1001',
    name: 'Creme Hidratante',
    model: 'BN-001',
    quantity: 1,
    price: 19.9,
    total: 19.9,
    tax: 0,
    reward: 0,
  },
  {
    order_product_id: 'op2',
    order_id: 'o3001',
    product_id: 'p1002',
    name: 'Sabonete Natural',
    model: 'BN-002',
    quantity: 1,
    price: 12.5,
    total: 12.5,
    tax: 0,
    reward: 0,
  },
  {
    order_product_id: 'op3',
    order_id: 'o3002',
    product_id: 'p1001',
    name: 'Creme Hidratante',
    model: 'BN-001',
    quantity: 1,
    price: 19.9,
    total: 19.9,
    tax: 0,
    reward: 0,
  },
  {
    order_product_id: 'op4',
    order_id: 'o3003',
    product_id: 'p1003',
    name: 'Bálsamo Labial',
    model: 'BN-003',
    quantity: 1,
    price: 7.99,
    total: 7.99,
    tax: 0,
    reward: 0,
  },
];

export const mockMyFormulaOrderStatuses: MyFormulaOrderStatus[] = [
  { order_status_id: '1', language_id: 2, name: 'Pendente' },
  { order_status_id: '2', language_id: 2, name: 'Em processamento' },
  { order_status_id: '3', language_id: 2, name: 'Enviado' },
  { order_status_id: '5', language_id: 2, name: 'Concluído' },
  { order_status_id: '7', language_id: 2, name: 'Cancelado' },
];

export const mockMyFormulaProducts: MyFormulaProduct[] = [
  {
    product_id: 'mf_p1001',
    model: 'MF-001',
    sku: 'SKU-001',
    price: 29.9,
    quantity: 20,
    status: true,
    date_added: d(60),
    description: { product_id: 'mf_p1001', language_id: 2, name: 'Multivitamínico', description: 'Fórmula diária para energia e bem-estar.' } satisfies MyFormulaProductDescription,
  },
  {
    product_id: 'mf_p1002',
    model: 'MF-002',
    sku: 'SKU-002',
    price: 19.5,
    quantity: 7,
    status: true,
    date_added: d(30),
    description: { product_id: 'mf_p1002', language_id: 2, name: 'Ómega 3', description: 'Suporte cardiovascular e anti-inflamatório.' } satisfies MyFormulaProductDescription,
  },
];

export const mockMyFormulaCustomers: MyFormulaCustomer[] = [
  {
    customer_id: 'mf_c2001',
    firstname: 'Joana',
    lastname: 'Pereira',
    email: 'joana.pereira@example.com',
    telephone: '+351 910 333 333',
    status: true,
    date_added: d(140),
  },
  {
    customer_id: 'mf_c2002',
    firstname: 'Miguel',
    lastname: 'Costa',
    email: 'miguel.costa@example.com',
    telephone: '+351 910 444 444',
    status: true,
    date_added: d(95),
  },
];

export const mockMyFormulaOrders: MyFormulaOrder[] = [
  {
    order_id: 'mf_o3001',
    invoice_no: null,
    store_name: 'MyFormula',
    customer_id: 'mf_c2001',
    firstname: 'Joana',
    lastname: 'Pereira',
    email: 'joana.pereira@example.com',
    telephone: '+351 910 333 333',
    total: 49.4,
    order_status_id: '2',
    date_added: d(6),
    date_modified: d(5),
    payment_method: 'Cartão',
    payment_code: 'card',
  },
  {
    order_id: 'mf_o3002',
    invoice_no: null,
    store_name: 'MyFormula',
    customer_id: 'mf_c2002',
    firstname: 'Miguel',
    lastname: 'Costa',
    email: 'miguel.costa@example.com',
    telephone: '+351 910 444 444',
    total: 29.9,
    order_status_id: '5',
    date_added: d(14),
    date_modified: d(12),
    payment_method: 'MBWay',
    payment_code: 'mbway',
  },
];

export const mockMyFormulaOrderProducts: MyFormulaOrderProduct[] = [
  {
    order_product_id: 'mf_op1',
    order_id: 'mf_o3001',
    product_id: 'mf_p1001',
    name: 'Multivitamínico',
    model: 'MF-001',
    quantity: 1,
    price: 29.9,
    total: 29.9,
    tax: 0,
  },
  {
    order_product_id: 'mf_op2',
    order_id: 'mf_o3001',
    product_id: 'mf_p1002',
    name: 'Ómega 3',
    model: 'MF-002',
    quantity: 1,
    price: 19.5,
    total: 19.5,
    tax: 0,
  },
  {
    order_product_id: 'mf_op3',
    order_id: 'mf_o3002',
    product_id: 'mf_p1001',
    name: 'Multivitamínico',
    model: 'MF-001',
    quantity: 1,
    price: 29.9,
    total: 29.9,
    tax: 0,
  },
];

export const mockMyFormulaQuizzes: MyFormulaQuiz[] = [
  {
    quiz_id: 'q1',
    date_added: d(2),
    post: {
      name: 'Joana Pereira',
      email: 'joana.pereira@example.com',
      gender: 'female',
      birthdate: '1990-05-10',
      height: 165,
      weight: 61,
      improve_health: 'A,B',
      step: 'plans',
    },
  },
  {
    quiz_id: 'q2',
    date_added: d(9),
    post: {
      name: 'Miguel Costa',
      email: 'miguel.costa@example.com',
      gender: 'male',
      birthdate: '1984-11-22',
      height: 178,
      weight: 82,
      improve_health: 'G',
      step: 'profile',
    },
  },
];

export const mockEspacoAbsolutoUserGroups: EspacoAbsolutoUserGroup[] = [
  { id: 1, name: 'Instagram', dashboard: true, is_active: true, created_at: d(220), updated_at: d(20) },
  { id: 2, name: 'WhatsApp', dashboard: true, is_active: true, created_at: d(220), updated_at: d(18) },
  { id: 3, name: 'Indicação', dashboard: true, is_active: true, created_at: d(220), updated_at: d(12) },
  { id: 4, name: 'Google', dashboard: true, is_active: true, created_at: d(220), updated_at: d(8) },
  { id: 5, name: 'Newsletter', dashboard: false, is_active: true, created_at: d(220), updated_at: d(30) },
];

export const mockEspacoAbsolutoCustomers: EspacoAbsolutoCustomer[] = [
  {
    id: 1001,
    name: 'Ana Silva',
    email: 'ana.silva@example.com',
    phone: '+351 912 345 678',
    origin: 'Instagram',
    status: true,
    registered_at: d(40),
    last_seen_at: d(2),
    created_at: d(40),
    updated_at: d(2),
  },
  {
    id: 1002,
    name: 'Miguel Costa',
    email: 'miguel.costa@example.com',
    phone: '+351 913 111 222',
    origin: 'Indicação',
    status: true,
    registered_at: d(18),
    last_seen_at: d(6),
    created_at: d(18),
    updated_at: d(6),
  },
  {
    id: 1003,
    name: 'Carla Pereira',
    email: 'carla.pereira@example.com',
    phone: '+351 914 555 999',
    origin: 'Google',
    status: false,
    registered_at: d(120),
    last_seen_at: null,
    created_at: d(120),
    updated_at: d(50),
  },
];

export const mockEspacoAbsolutoUserMessages: EspacoAbsolutoUserMessage[] = [
  {
    id: 5001,
    user_id: 1001,
    email: 'ana.silva@example.com',
    subject: 'Primeiro contacto',
    message: 'Olá! Gostava de saber mais sobre tratamentos faciais.',
    note: null,
    date: d(40),
    created_at: d(40),
    updated_at: d(40),
  },
  {
    id: 5002,
    user_id: 1002,
    email: 'miguel.costa@example.com',
    subject: 'Marcação',
    message: 'Boa tarde, conseguem agendar para esta semana?',
    note: 'Preferência por final do dia.',
    date: d(18),
    created_at: d(18),
    updated_at: d(10),
  },
];

export const mockEspacoAbsolutoAppointments: EspacoAbsolutoAppointment[] = [
  {
    id: 8001,
    customer_id: 1001,
    treatment: 'Limpeza de Pele',
    scheduled_at: d(1),
    status: 'completed',
    notes: null,
    created_at: d(3),
    updated_at: d(1),
  },
  {
    id: 8002,
    customer_id: 1002,
    treatment: 'Massagem Relaxamento',
    scheduled_at: d(0),
    status: 'scheduled',
    notes: 'Confirmar na véspera.',
    created_at: d(2),
    updated_at: d(0),
  },
];

export const mockRoles: Role[] = [
  {
    id: 'rol1',
    name: 'admin',
    display_name: 'Administrador',
    description: 'Acesso total ao sistema.',
    permissions: ['*'],
    is_active: true,
    createdAt: d(365),
    updatedAt: d(2),
  },
  {
    id: 'rol2',
    name: 'manager',
    display_name: 'Gestor',
    description: 'Gestão de equipas e operações.',
    permissions: ['users.read', 'users.write', 'departments.read', 'departments.write'],
    is_active: true,
    createdAt: d(300),
    updatedAt: d(10),
  },
  {
    id: 'rol3',
    name: 'agent',
    display_name: 'Agente',
    description: 'Operação diária.',
    permissions: ['users.read', 'departments.read'],
    is_active: true,
    createdAt: d(250),
    updatedAt: d(20),
  },
  {
    id: 'rol4',
    name: 'customer',
    display_name: 'Cliente',
    description: 'Acesso limitado.',
    permissions: [],
    is_active: true,
    createdAt: d(200),
    updatedAt: d(30),
  },
  {
    id: 'rol5',
    name: 'supervisor',
    display_name: 'Supervisor',
    description: 'Aprovação e supervisão.',
    permissions: ['users.read', 'departments.read', 'reports.read'],
    is_active: true,
    createdAt: d(180),
    updatedAt: d(5),
  },
];

export const mockEmployees: Employee[] = [
  {
    id: 'emp1',
    employee_code: 'EMP001',
    name: 'João Silva',
    email: 'joao.silva@empresa.com',
    nif: '123456789',
    document_type: 'CC',
    document_number: '12345678',
    document_expiration_date: d(-365).split('T')[0],
    nis: '12345678901',
    birth_date: '1990-04-12',
    gender: 'male',
    nationality: 'PT',
    marital_status: 'single',
    spouse_name: null,
    spouse_nif: null,
    spouse_joint_irs: null,
    has_children: false,
    children_data: [],
    phone: '+351 910 000 010',
    emergency_contact: 'Maria Silva',
    emergency_phone: '+351 910 000 011',
    address: 'Rua Central',
    address_number: '10',
    complement: null,
    neighborhood: null,
    city: 'Lisboa',
    state: 'Lisboa',
    zip_code: '1000-000',
    position: 'Analista',
    department_id: 'dep2',
    company_id: 'cmp1',
    hire_date: '2024-02-12',
    termination_date: null,
    salary: 1450,
    hourly_rate: 9.5,
    vacation_days_balance: 18,
    last_vacation_calculation: d(10).split('T')[0],
    employment_type: 'full_time',
    contract_duration: null,
    auto_renew: null,
    status: 'active',
    bank_name: 'CGD',
    bank_agency: '001',
    bank_account: 'PT50 0000 0000 0000 0000 0000 0',
    account_type: 'IBAN',
    notes: null,
    photo_path: null,
    has_disability: false,
    disability_declarant: false,
    disability_spouse: false,
    disability_dependents: 0,
    documents: [],
    medical_aptitude_date: d(60).split('T')[0],
    medical_status: 'fit',
    createdAt: d(120),
    updatedAt: d(2),
  },
  {
    id: 'emp2',
    employee_code: 'EMP002',
    name: 'Mariana Costa',
    email: 'mariana.costa@empresa.com',
    nif: '987654321',
    document_type: 'CC',
    document_number: '87654321',
    document_expiration_date: d(-180).split('T')[0],
    nis: '10987654321',
    birth_date: '1992-11-02',
    gender: 'female',
    nationality: 'PT',
    marital_status: 'married',
    spouse_name: 'Rui Costa',
    spouse_nif: '111222333',
    spouse_joint_irs: true,
    has_children: true,
    children_data: [{ name: 'Inês', birth_date: '2018-06-01' }],
    phone: '+351 910 000 020',
    emergency_contact: 'Rui Costa',
    emergency_phone: '+351 910 000 021',
    address: 'Avenida do Parque',
    address_number: '120',
    complement: '3º D',
    neighborhood: null,
    city: 'Lisboa',
    state: 'Lisboa',
    zip_code: '1500-100',
    position: 'RH',
    department_id: 'dep1',
    company_id: 'cmp1',
    hire_date: '2023-09-01',
    termination_date: null,
    salary: 1600,
    hourly_rate: null,
    vacation_days_balance: 22,
    last_vacation_calculation: d(30).split('T')[0],
    employment_type: 'full_time',
    contract_duration: null,
    auto_renew: null,
    status: 'active',
    bank_name: 'Millennium',
    bank_agency: '1234',
    bank_account: 'PT50 1111 1111 1111 1111 1111 1',
    account_type: 'IBAN',
    notes: 'Preferência por contacto via email.',
    photo_path: null,
    has_disability: false,
    disability_declarant: false,
    disability_spouse: false,
    disability_dependents: 0,
    documents: [],
    medical_aptitude_date: d(120).split('T')[0],
    medical_status: 'fit',
    createdAt: d(200),
    updatedAt: d(10),
  },
  {
    id: 'emp3',
    employee_code: 'EMP003',
    name: 'Pedro Almeida',
    email: 'pedro.almeida@empresa.com',
    nif: null,
    document_type: null,
    document_number: null,
    document_expiration_date: null,
    nis: null,
    birth_date: '1988-01-18',
    gender: 'male',
    nationality: 'PT',
    marital_status: 'single',
    spouse_name: null,
    spouse_nif: null,
    spouse_joint_irs: null,
    has_children: false,
    children_data: [],
    phone: '+351 910 000 030',
    emergency_contact: null,
    emergency_phone: null,
    address: null,
    address_number: null,
    complement: null,
    neighborhood: null,
    city: 'Porto',
    state: 'Porto',
    zip_code: null,
    position: 'Operações',
    department_id: 'dep3',
    company_id: 'cmp2',
    hire_date: '2022-05-20',
    termination_date: null,
    salary: 1300,
    hourly_rate: 8.0,
    vacation_days_balance: 10,
    last_vacation_calculation: d(90).split('T')[0],
    employment_type: 'part_time',
    contract_duration: 12,
    auto_renew: true,
    status: 'on_leave',
    bank_name: null,
    bank_agency: null,
    bank_account: null,
    account_type: null,
    notes: null,
    photo_path: null,
    has_disability: false,
    disability_declarant: false,
    disability_spouse: false,
    disability_dependents: 0,
    documents: [],
    medical_aptitude_date: null,
    medical_status: 'fit',
    createdAt: d(500),
    updatedAt: d(90),
  },
];

export const mockTimesheets: Timesheet[] = [
  {
    id: 'ts1',
    employee_id: 'emp1',
    company_id: 'cmp1',
    work_date: d(2).split('T')[0],
    clock_in: '09:03',
    lunch_start: '13:00',
    lunch_end: '14:00',
    clock_out: '18:02',
    total_hours: 8.0,
    lunch_hours: 1.0,
    overtime_hours: 0.0,
    expected_hours: 8.0,
    status: 'late',
    day_type: 'workday',
    ip_address: '192.168.1.10',
    location: 'Escritório',
    device_info: 'Web',
    employee_notes: null,
    manager_notes: null,
    approved_by: null,
    approved_at: null,
    createdAt: d(2),
    updatedAt: d(2),
  },
  {
    id: 'ts2',
    employee_id: 'emp2',
    company_id: 'cmp1',
    work_date: d(2).split('T')[0],
    clock_in: '09:00',
    lunch_start: '13:00',
    lunch_end: '14:00',
    clock_out: '18:10',
    total_hours: 8.17,
    lunch_hours: 1.0,
    overtime_hours: 0.17,
    expected_hours: 8.0,
    status: 'present',
    day_type: 'workday',
    ip_address: '192.168.1.11',
    location: 'Escritório',
    device_info: 'Web',
    employee_notes: null,
    manager_notes: null,
    approved_by: 'usr2',
    approved_at: d(1),
    createdAt: d(2),
    updatedAt: d(1),
  },
  {
    id: 'ts3',
    employee_id: 'emp3',
    company_id: 'cmp2',
    work_date: d(2).split('T')[0],
    clock_in: null,
    lunch_start: null,
    lunch_end: null,
    clock_out: null,
    total_hours: 0,
    lunch_hours: 0,
    overtime_hours: 0,
    expected_hours: 8.0,
    status: 'vacation',
    day_type: 'vacation',
    ip_address: null,
    location: null,
    device_info: null,
    employee_notes: null,
    manager_notes: null,
    approved_by: null,
    approved_at: null,
    createdAt: d(2),
    updatedAt: d(2),
  },
  {
    id: 'ts4',
    employee_id: 'emp2',
    company_id: 'cmp1',
    work_date: d(3).split('T')[0],
    clock_in: null,
    lunch_start: null,
    lunch_end: null,
    clock_out: null,
    total_hours: 0,
    lunch_hours: 0,
    overtime_hours: 0,
    expected_hours: 8.0,
    status: 'absent',
    day_type: 'workday',
    ip_address: null,
    location: null,
    device_info: null,
    employee_notes: 'Sem condições de comparecer.',
    manager_notes: null,
    approved_by: null,
    approved_at: null,
    createdAt: d(3),
    updatedAt: d(3),
  },
];

export const mockPayrolls: Payroll[] = [
  {
    id: 'pay1',
    employee_id: 'emp1',
    company_id: 'cmp1',
    reference_month: 1,
    reference_year: 2026,
    base_salary: 1450,
    overtime_hours: 5,
    overtime_amount: 100,
    holiday_allowance: 0,
    christmas_allowance: 0,
    meal_allowance: 100,
    transport_allowance: 0,
    other_allowances: 0,
    social_security_employee: 170,
    social_security_employer: 0,
    irs_withholding: 120,
    union_fee: 0,
    other_deductions: 0,
    gross_total: 1650,
    total_deductions: 290,
    net_total: 1360,
    status: 'paid',
    pdf_path: null,
    notes: null,
    created_by: 'usr1',
    approved_by: 'usr2',
    approved_at: d(40),
    createdAt: d(45),
    updatedAt: d(40),
  },
  {
    id: 'pay2',
    employee_id: 'emp2',
    company_id: 'cmp1',
    reference_month: 1,
    reference_year: 2026,
    base_salary: 1600,
    overtime_hours: 0,
    overtime_amount: 0,
    holiday_allowance: 0,
    christmas_allowance: 0,
    meal_allowance: 110,
    transport_allowance: 0,
    other_allowances: 0,
    social_security_employee: 188,
    social_security_employer: 0,
    irs_withholding: 150,
    union_fee: 0,
    other_deductions: 0,
    gross_total: 1710,
    total_deductions: 338,
    net_total: 1372,
    status: 'approved',
    pdf_path: null,
    notes: 'Aguardando pagamento.',
    created_by: 'usr1',
    approved_by: 'usr2',
    approved_at: d(12),
    createdAt: d(20),
    updatedAt: d(12),
  },
  {
    id: 'pay3',
    employee_id: 'emp3',
    company_id: 'cmp2',
    reference_month: 12,
    reference_year: 2025,
    base_salary: 1300,
    overtime_hours: 2,
    overtime_amount: 40,
    holiday_allowance: 0,
    christmas_allowance: 100,
    meal_allowance: 90,
    transport_allowance: 0,
    other_allowances: 0,
    social_security_employee: 160,
    social_security_employer: 0,
    irs_withholding: 80,
    union_fee: 5,
    other_deductions: 0,
    gross_total: 1530,
    total_deductions: 245,
    net_total: 1285,
    status: 'draft',
    pdf_path: null,
    notes: null,
    created_by: 'usr1',
    approved_by: null,
    approved_at: null,
    createdAt: d(90),
    updatedAt: d(90),
  },
];

export const mockVacations: Vacation[] = [
  {
    id: 'vac1',
    employee_id: 'emp1',
    company_id: 'cmp1',
    start_date: '2026-06-10',
    end_date: '2026-06-21',
    requested_days: 12,
    approved_days: 12,
    vacation_year: 2026,
    vacation_type: 'annual_leave',
    status: 'approved',
    requested_at: d(80),
    approved_at: d(78),
    rejected_at: null,
    employee_notes: null,
    manager_notes: 'Aprovado conforme planeamento.',
    rejection_reason: null,
    approved_by: 'usr2',
    rejected_by: null,
    created_by: 'usr1',
    createdAt: d(80),
    updatedAt: d(78),
  },
  {
    id: 'vac2',
    employee_id: 'emp2',
    company_id: 'cmp1',
    start_date: '2026-04-01',
    end_date: '2026-04-05',
    requested_days: 5,
    approved_days: null,
    vacation_year: 2026,
    vacation_type: 'annual_leave',
    status: 'pending',
    requested_at: d(15),
    approved_at: null,
    rejected_at: null,
    employee_notes: 'Preciso para assuntos pessoais.',
    manager_notes: null,
    rejection_reason: null,
    approved_by: null,
    rejected_by: null,
    created_by: 'usr1',
    createdAt: d(15),
    updatedAt: d(15),
  },
  {
    id: 'vac3',
    employee_id: 'emp3',
    company_id: 'cmp2',
    start_date: '2026-03-18',
    end_date: '2026-03-22',
    requested_days: 5,
    approved_days: 5,
    vacation_year: 2026,
    vacation_type: 'sick_leave',
    status: 'approved',
    requested_at: d(30),
    approved_at: d(29),
    rejected_at: null,
    employee_notes: 'Atestado médico enviado.',
    manager_notes: null,
    rejection_reason: null,
    approved_by: 'usr2',
    rejected_by: null,
    created_by: 'usr1',
    createdAt: d(30),
    updatedAt: d(29),
  },
  {
    id: 'vac4',
    employee_id: 'emp2',
    company_id: 'cmp1',
    start_date: '2026-02-10',
    end_date: '2026-02-12',
    requested_days: 3,
    approved_days: 0,
    vacation_year: 2026,
    vacation_type: 'other',
    status: 'rejected',
    requested_at: d(50),
    approved_at: d(49),
    rejected_at: d(49),
    employee_notes: null,
    manager_notes: 'Período conflita com operação.',
    rejection_reason: 'Conflito com escala / falta de cobertura.',
    approved_by: 'usr2',
    rejected_by: 'usr2',
    created_by: 'usr1',
    createdAt: d(50),
    updatedAt: d(49),
  },
];

export const mockFinanceBankAccounts: FinanceBankAccount[] = [
  {
    id: 'fba1',
    company_id: 'cmp1',
    name: 'Conta Principal',
    bank_name: 'Millennium',
    account_number: 'PT50 0000 0000 0000 0000 0000 0',
    currency: 'EUR',
    initial_balance: 10000,
    current_balance: 12500,
    is_active: true,
    createdAt: d(200),
    updatedAt: d(3),
  },
  {
    id: 'fba2',
    company_id: 'cmp1',
    name: 'Conta Marketing',
    bank_name: 'Santander',
    account_number: 'PT50 1111 1111 1111 1111 1111 1',
    currency: 'EUR',
    initial_balance: 2500,
    current_balance: 1800,
    is_active: true,
    createdAt: d(180),
    updatedAt: d(20),
  },
  {
    id: 'fba3',
    company_id: 'cmp2',
    name: 'Conta Operações',
    bank_name: 'CGD',
    account_number: 'PT50 2222 2222 2222 2222 2222 2',
    currency: 'EUR',
    initial_balance: 8000,
    current_balance: 7600,
    is_active: true,
    createdAt: d(150),
    updatedAt: d(12),
  },
];

export const mockFinanceCategories: FinanceCategory[] = [
  {
    id: 'fcat1',
    company_id: 'cmp1',
    parent_id: null,
    name: 'Vendas',
    type: 'income',
    color: '#22c55e',
    is_active: true,
    createdAt: d(220),
    updatedAt: d(4),
  },
  {
    id: 'fcat2',
    company_id: 'cmp1',
    parent_id: null,
    name: 'Marketing',
    type: 'expense',
    color: '#f97316',
    is_active: true,
    createdAt: d(220),
    updatedAt: d(4),
  },
  {
    id: 'fcat3',
    company_id: 'cmp1',
    parent_id: 'fcat2',
    name: 'Google Ads',
    type: 'expense',
    color: '#fb7185',
    is_active: true,
    createdAt: d(200),
    updatedAt: d(10),
  },
  {
    id: 'fcat4',
    company_id: 'cmp2',
    parent_id: null,
    name: 'Serviços',
    type: 'income',
    color: '#38bdf8',
    is_active: true,
    createdAt: d(180),
    updatedAt: d(20),
  },
];

export const mockFinanceCostCenters: FinanceCostCenter[] = [
  {
    id: 'fcc1',
    company_id: 'cmp1',
    name: 'Sede',
    code: 'HQ',
    createdAt: d(240),
    updatedAt: d(30),
  },
  {
    id: 'fcc2',
    company_id: 'cmp1',
    name: 'Loja Online',
    code: 'E-COM',
    createdAt: d(180),
    updatedAt: d(15),
  },
  {
    id: 'fcc3',
    company_id: 'cmp2',
    name: 'Operações',
    code: 'OPS',
    createdAt: d(200),
    updatedAt: d(40),
  },
];

export const mockFinanceTransactions: FinanceTransaction[] = [
  {
    id: 'ftx1',
    company_id: 'cmp1',
    description: 'Fatura #2026-0001',
    notes: 'Pagamento recebido por transferência.',
    amount: 2500,
    due_date: d(15),
    paid_at: d(12),
    type: 'income',
    status: 'paid',
    category_id: 'fcat1',
    cost_center_id: 'fcc2',
    bank_account_id: 'fba1',
    payer_type: null,
    payer_id: null,
    reference_type: null,
    reference_id: null,
    createdAt: d(20),
    updatedAt: d(12),
  },
  {
    id: 'ftx2',
    company_id: 'cmp1',
    description: 'Google Ads - Fevereiro',
    notes: null,
    amount: 700,
    due_date: d(7),
    paid_at: null,
    type: 'expense',
    status: 'pending',
    category_id: 'fcat3',
    cost_center_id: 'fcc2',
    bank_account_id: 'fba2',
    payer_type: null,
    payer_id: null,
    reference_type: null,
    reference_id: null,
    createdAt: d(7),
    updatedAt: d(7),
  },
  {
    id: 'ftx3',
    company_id: 'cmp2',
    description: 'Serviço Mensal - Cliente X',
    notes: null,
    amount: 1200,
    due_date: d(5),
    paid_at: null,
    type: 'income',
    status: 'late',
    category_id: 'fcat4',
    cost_center_id: 'fcc3',
    bank_account_id: 'fba3',
    payer_type: null,
    payer_id: null,
    reference_type: null,
    reference_id: null,
    createdAt: d(40),
    updatedAt: d(1),
  },
];

export const mockSystemLogs: SystemLog[] = [
  {
    id: 'log1',
    user_id: 'usr1',
    action: 'auth.login',
    model_type: 'App\\Models\\User',
    model_id: 'usr1',
    description: 'Login efetuado com sucesso.',
    ip_address: '127.0.0.1',
    user_agent: 'Mozilla/5.0',
    level: 'info',
    context: { method: 'password' },
    created_at: d(1),
  },
  {
    id: 'log2',
    user_id: 'usr2',
    action: 'admin.user.update',
    model_type: 'App\\Models\\User',
    model_id: 'usr3',
    description: 'Utilizador atualizado.',
    ip_address: '127.0.0.1',
    user_agent: 'Mozilla/5.0',
    level: 'warning',
    context: { fields: ['phone', 'department_id'] },
    created_at: d(3),
  },
  {
    id: 'log3',
    user_id: null,
    action: 'system.cron',
    model_type: null,
    model_id: null,
    description: 'Tarefa agendada executada.',
    ip_address: null,
    user_agent: null,
    level: 'debug',
    context: { job: 'sync_metrics', duration_ms: 842 },
    created_at: d(4),
  },
  {
    id: 'log4',
    user_id: 'usr1',
    action: 'finance.transaction.create',
    model_type: 'Modules\\Finance\\app\\Models\\FinanceTransaction',
    model_id: 'ftx1',
    description: 'Lançamento criado.',
    ip_address: '127.0.0.1',
    user_agent: 'Mozilla/5.0',
    level: 'info',
    context: { type: 'income', amount: 2500, currency: 'EUR' },
    created_at: d(5),
  },
  {
    id: 'log5',
    user_id: 'usr1',
    action: 'system.error',
    model_type: null,
    model_id: null,
    description: 'Erro inesperado durante processamento.',
    ip_address: '127.0.0.1',
    user_agent: 'Mozilla/5.0',
    level: 'error',
    context: { code: 'E_UNKNOWN', trace_id: 'trc_123' },
    created_at: d(6),
  },
];

export const mockTasks: Task[] = [
  {
    id: 'tsk1',
    user_id: 'usr1',
    title: 'Preparar relatório semanal',
    description: 'Rever métricas e preparar resumo.',
    priority: 'high',
    status: 'in_progress',
    due_date: d(0),
    start_date: d(2),
    completed_at: null,
    is_all_day: false,
    location: null,
    notes: 'Incluir Financeiro e Campanhas.',
    attachments: [],
    taskable_type: null,
    taskable_id: null,
    calendar_event_id: null,
    recurrence_rule: null,
    is_private: false,
    shared_with_user_ids: ['usr2'],
    createdAt: d(10),
    updatedAt: d(1),
  },
  {
    id: 'tsk2',
    user_id: 'usr1',
    title: 'Atualizar lista de contactos',
    description: null,
    priority: 'medium',
    status: 'pending',
    due_date: d(3),
    start_date: null,
    completed_at: null,
    is_all_day: true,
    location: null,
    notes: null,
    attachments: [],
    taskable_type: null,
    taskable_id: null,
    calendar_event_id: null,
    recurrence_rule: null,
    is_private: true,
    shared_with_user_ids: [],
    createdAt: d(7),
    updatedAt: d(7),
  },
  {
    id: 'tsk3',
    user_id: 'usr2',
    title: 'Tarefa de outro utilizador',
    description: null,
    priority: 'low',
    status: 'pending',
    due_date: d(5),
    start_date: null,
    completed_at: null,
    is_all_day: false,
    location: null,
    notes: null,
    attachments: [],
    taskable_type: null,
    taskable_id: null,
    calendar_event_id: null,
    recurrence_rule: null,
    is_private: false,
    shared_with_user_ids: ['usr1'],
    createdAt: d(6),
    updatedAt: d(6),
  },
];

export const mockPersonalNotes: PersonalNote[] = [
  {
    id: 'note1',
    user_id: 'usr1',
    title: 'Ideias para a campanha',
    content: 'Testar segmento VIP e variar subject lines.',
    color: '#38bdf8',
    is_favorite: true,
    last_modified_by: 'usr1',
    shared_with_user_ids: [],
    createdAt: d(30),
    updatedAt: d(2),
  },
  {
    id: 'note2',
    user_id: 'usr1',
    title: 'Checklist do mês',
    content: '- Rever CRM\n- Fechar contas\n- Limpar listas\n',
    color: '#f97316',
    is_favorite: false,
    last_modified_by: 'usr1',
    shared_with_user_ids: ['usr2'],
    createdAt: d(20),
    updatedAt: d(5),
  },
  {
    id: 'note3',
    user_id: 'usr2',
    title: 'Nota de outro utilizador',
    content: 'Esta não deve aparecer em “Minhas Anotações” do usr1.',
    color: null,
    is_favorite: false,
    last_modified_by: 'usr2',
    shared_with_user_ids: [],
    createdAt: d(12),
    updatedAt: d(12),
  },
];
