---
version: 2
backend:
  tasks:
    # Instala dependências do Laravel na pasta do projeto
    - cd laravel && composer install --no-dev --optimize-autoloader

    # Gera caches do Laravel
    - cd laravel && php artisan config:cache
    - cd laravel && php artisan route:cache
    - cd laravel && php artisan view:cache

    # Migra o banco de dados
    - cd laravel && php artisan migrate --force

    # Copia apenas os arquivos públicos para a pasta public_html
    - cp -r laravel/public/* /home/USERNAME/public_html/

hooks:
  after_deploy:
    - echo "Deploy Laravel realizado com sucesso!"
